import { Color } from 'three'

export const AtmosphericFogShader = {
  uniforms: {
    tDiffuse: { value: null },
    tDepth: { value: null },
    time: { value: 0 },
    strength: { value: 0 },
    cameraNear: { value: 1 },
    cameraFar: { value: 3000 },
    fogColor: { value: new Color(0xb8c2c8) },
    fogNear: { value: 700 },
    fogFar: { value: 2800 },
    fogDensity: { value: 0.00012 },
    fogOpacity: { value: 0.45 },
    backgroundFog: { value: 0.18 },
  },
  vertexShader: [
    'varying vec2 vUv;',
    'void main() {',
    '  vUv = uv;',
    '  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);',
    '}',
  ].join('\n'),
  fragmentShader: [
    '#include <packing>',
    'uniform sampler2D tDiffuse;',
    'uniform sampler2D tDepth;',
    'uniform float time;',
    'uniform float strength;',
    'uniform float cameraNear;',
    'uniform float cameraFar;',
    'uniform vec3 fogColor;',
    'uniform float fogNear;',
    'uniform float fogFar;',
    'uniform float fogDensity;',
    'uniform float fogOpacity;',
    'uniform float backgroundFog;',
    'varying vec2 vUv;',
    'float hash(vec2 p) {',
    '  p = fract(p * vec2(123.34, 456.21));',
    '  p += dot(p, p + 45.32);',
    '  return fract(p.x * p.y);',
    '}',
    'float valueNoise(vec2 p) {',
    '  vec2 i = floor(p);',
    '  vec2 f = fract(p);',
    '  f = f * f * (3.0 - 2.0 * f);',
    '  float a = hash(i);',
    '  float b = hash(i + vec2(1.0, 0.0));',
    '  float c = hash(i + vec2(0.0, 1.0));',
    '  float d = hash(i + vec2(1.0, 1.0));',
    '  return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);',
    '}',
    'void main() {',
    '  vec4 color = texture2D(tDiffuse, vUv);',
    '  float depth = texture2D(tDepth, vUv).x;',
    '  float hasSceneDepth = 1.0 - step(0.9999, depth);',
    '  float viewDistance = -perspectiveDepthToViewZ(depth, cameraNear, cameraFar);',
    '  float rangeFog = smoothstep(fogNear, fogFar, viewDistance);',
    '  const float LOG2 = 1.442695;',
    '  float expFog = 1.0 - exp2(-fogDensity * fogDensity * viewDistance * viewDistance * LOG2);',
    '  float depthFog = max(rangeFog, expFog) * hasSceneDepth;',
    '  vec2 centeredUv = vUv - vec2(0.5);',
    '  float vignette = smoothstep(0.26, 0.78, length(centeredUv * vec2(1.0, 0.82)));',
    // Particles write no depth (transparent shader materials), so we can't gate
    // fog by hasSceneDepth — every pixel reads as "background" and bleaches the
    // foreground particles. Use color luminance instead: skip the haze where the
    // frame already has bright pixels (particles), apply it where the frame is
    // near-black (the actual void). Plus a sky-only vertical gradient so the
    // haze concentrates in the upper region where atmospheric depth reads.
    '  float lum = dot(color.rgb, vec3(0.299, 0.587, 0.114));',
    '  float voidMask = 1.0 - smoothstep(0.02, 0.18, lum);',
    '  float skyGradient = 1.0 - smoothstep(0.15, 0.85, vUv.y);',
    '  float drift = valueNoise(vUv * vec2(4.0, 2.0) + vec2(time * 0.003, -time * 0.0015));',
    '  float backgroundHaze = backgroundFog * skyGradient * voidMask * mix(0.85, 1.15, drift);',
    '  float fogFactor = depthFog * mix(0.4, 1.0, vignette) + backgroundHaze;',
    '  fogFactor = clamp(fogFactor * fogOpacity * strength, 0.0, 1.0);',
    '  gl_FragColor = vec4(mix(color.rgb, fogColor, fogFactor), color.a);',
    '}',
  ].join('\n'),
}

export default AtmosphericFogShader
